from pathlib import Path
import re

path = Path('content/jaipuria-jaipur-mba/overview.html')
html = path.read_text(encoding='utf-8')

faq = '''<section class="section faq" id="faq"><h2>Jaipuria Jaipur MBA FAQs</h2>
<details><summary>Is Jaipuria Jaipur a good option for an MBA?</summary><p>Jaipuria Jaipur can be a relevant option for students looking for a private management institute with a two-year full-time PGDM, MBA equivalence through AIU recognition, multiple management career areas and structured industry exposure. The programme combines classroom learning with case analysis, projects, internships and professional-development activities. However, whether it is a good choice depends on your target career, entrance-score profile, budget and the alternatives available at your percentile. Students should also remember that the latest placement figures published by Jaipuria are combined across Jaipur, Noida, Lucknow and Indore rather than being Jaipur-campus-only figures. Therefore, compare the fee, placement transparency, preferred specialization and location before making the final decision.</p></details>
<details><summary>What is the eligibility for Jaipuria Jaipur PGDM/MBA?</summary><p>Applicants must have a bachelor's degree from a recognised Indian university with at least 50% marks or an equivalent CGPA. Final-year students can also apply, subject to the institute's conditions for completing the degree and submitting the required proof within the specified timeline. For the current admission cycle, Jaipuria lists CAT, XAT, CMAT, MAT and GMAT as accepted aptitude tests. Meeting the academic eligibility requirement makes you eligible to apply, but it does not by itself guarantee selection because the institute evaluates the overall profile through its selection process.</p></details>
<details><summary>Which entrance exams are accepted by Jaipuria Jaipur?</summary><p>Jaipuria accepts valid scores from CAT, XAT, CMAT, MAT and GMAT for its PGDM admission process. Applicants use the common Jaipuria application to indicate their preferred campus and programme and provide their relevant test score details. The exact test year mentioned in the admission notification changes with the admission cycle, so students should use the test combinations stated for their intended batch rather than relying on an older admission page. A valid entrance score is an important part of the application because the aptitude-test component carries 45% weightage in the published selection framework.</p></details>
<details><summary>What is the selection process for Jaipuria Jaipur?</summary><p>Jaipuria's published selection framework evaluates more than just the entrance-test percentile. The aptitude-test score carries 45%, case analysis carries 10%, and the personal interview carries 25%. Academic performance across Class X, Class XII and degree/postgraduate qualifications contributes 15%, while work experience, sports and extracurricular activities contribute 3% and diversity contributes 2%. This means an applicant with a strong test score still needs to perform well in the case analysis and interview and maintain a credible academic and overall profile. Shortlisted candidates are invited for the institute's evaluation process before the final admission decision is made.</p></details>
<details><summary>What is the fee for Jaipuria Jaipur PGDM?</summary><p>The official fee structure for the 2026-28 batch lists the Jaipuria Jaipur PGDM programme fee at ₹14.75 lakh for the full two-year programme. It is divided into six instalments: ₹2.70 lakh, ₹2.40 lakh, ₹2.40 lakh, ₹2.65 lakh, ₹2.30 lakh and ₹2.30 lakh. In addition, a refundable ₹15,000 security deposit is payable with the first instalment, while applicable GST or other taxes may be extra. Hostel accommodation is charged separately; the published 2026-27 hostel fee is ₹2.10 lakh for AC single occupancy and ₹1.40 lakh for AC double occupancy, with mess charges and the hostel security deposit additional.</p></details>
<details><summary>What is the placement scenario at Jaipuria Jaipur?</summary><p>Jaipuria's latest published placement information reports a ₹24.11 LPA highest CTC, ₹14.70 LPA average CTC for the top 10% of students and ₹13.18 LPA for the top 20%, along with more than 1,100 students placed and 350+ participating companies in the latest published cycle. The most important point for Jaipur applicants is that these placement numbers are presented as combined figures for Jaipuria's Jaipur, Noida, Lucknow and Indore campuses. They therefore should not be read as the guaranteed average or highest package for Jaipur campus alone. Students should use the figures as an overall indicator of the institute's recruiter ecosystem and ask for campus-specific outcomes when comparing offers.</p></details>
<details><summary>Does Jaipuria Jaipur offer scholarships?</summary><p>Yes. Jaipuria offers merit-based scholarships and other financial-support options. The published scholarship structure includes entrance-test-linked awards, with the current fee/admission information showing scholarships that can go up to ₹5 lakh depending on the qualifying score band and programme. Jaipuria also lists a sibling scholarship and education-loan assistance through partner banks and NBFCs. Scholarship availability, amount, eligibility conditions and the applicable test-year rules can change by batch, so students should verify the scholarship terms attached to their specific admission offer rather than deducting the maximum advertised scholarship automatically from the programme fee.</p></details>
<details><summary>Is hostel accommodation available at Jaipuria Jaipur?</summary><p>Yes. Jaipuria Jaipur provides hostel accommodation options for students, with published 2026-27 rates of ₹2.10 lakh per year for AC single occupancy and ₹1.40 lakh per year for AC double occupancy. A separate refundable hostel security deposit is payable, and mess charges are additional. Hostel allotment is subject to availability and the institute's allocation process, so students who want campus accommodation should check the latest hostel notice and complete the required process on time. When calculating the actual MBA budget, students should therefore consider tuition, security deposits, hostel and mess costs together rather than looking only at the ₹14.75 lakh programme fee.</p></details>
</section>'''

pattern = re.compile(r'<section class="section(?: faq)?" id="faq">.*?</section>', re.S)
new_html, count = pattern.subn(faq, html, count=1)
if count != 1:
    raise SystemExit('Jaipuria Jaipur FAQ section not found; no changes made.')
path.write_text(new_html, encoding='utf-8')
print('Updated Jaipuria Jaipur FAQ section with detailed answers.')
